# Generated by Django 4.0.6 on 2023-05-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='Время отправки')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Отправитель')),
                ('rate', models.IntegerField(verbose_name='Оценка')),
                ('text', models.CharField(max_length=2048, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Статус покупки')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='numbers_of_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='accounts.comment', verbose_name='Комментарии'),
        ),
    ]
