# Generated by Django 4.0.6 on 2023-05-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FM', 'Фермер'), ('BY', 'Покупатель'), ('AD', 'Админ')], default='BY', max_length=3, verbose_name='Роль'),
        ),
    ]
