# Generated by Django 4.0.6 on 2023-05-26 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
        migrations.AddField(
            model_name='chat',
            name='name1',
            field=models.CharField(max_length=255, null=True, verbose_name='Название чата1'),
        ),
        migrations.AddField(
            model_name='chat',
            name='name2',
            field=models.CharField(max_length=255, null=True, verbose_name='Название чата2'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель1'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель2'),
        ),
    ]
