# Generated by Django 4.0.6 on 2023-05-26 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=63, verbose_name='Название')),
                ('cost_retail', models.IntegerField(blank=True, null=True, verbose_name='Розничная цена')),
                ('cost_wholesale', models.IntegerField(blank=True, null=True, verbose_name='Оптовая цена')),
                ('doc', models.FileField(upload_to='uploads/', verbose_name='Фото')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата готовности')),
                ('farmer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
