# Generated by Django 4.0.6 on 2023-05-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('FM', 'Фермер'), ('SL', 'Покупатель'), ('AD', 'Админ')], default='SL', max_length=3, verbose_name='Роль'),
        ),
    ]
