# Generated by Django 4.0.6 on 2023-06-19 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_of_receive',
            field=models.DateField(blank=True, null=True, verbose_name='Дата получения заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items_name_123', to='accounts.orderitems', verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('CA', 'Карта'), ('BC', 'Юр. лицо'), ('CS', 'Наличные')], default='BY', max_length=3, null=True, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='Общая стоимость'),
        ),
        migrations.AddField(
            model_name='order',
            name='way_of_shipping',
            field=models.CharField(blank=True, choices=[('CA', 'Карта'), ('BC', 'Юр. лицо'), ('CS', 'Наличные')], default='BY', max_length=3, null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата покупки'),
        ),
    ]
