# Generated by Django 4.0.6 on 2023-05-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_message_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FM', 'Фермер'), ('SL', 'Покупатель'), ('AD', 'Админ')], default='SL', max_length=3, verbose_name='Роль'),
        ),
    ]
