# Generated by Django 4.0.6 on 2023-06-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_order_date_of_receive_order_items_order_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('CA', 'Карта'), ('BC', 'Юр. лицо'), ('CS', 'Наличные')], default='CA', max_length=3, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='way_of_shipping',
            field=models.CharField(blank=True, choices=[('CA', 'Самолет'), ('BC', 'Поезд'), ('KU', 'Курьер'), ('SA', 'Самовывоз')], default='SA', max_length=3, null=True, verbose_name='Способ доставки'),
        ),
    ]
