# Generated by Django 4.2.1 on 2023-05-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Количество товара"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="number_wholesale",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Мин. кол-во товара для оптовой закупки",
            ),
        ),
    ]
